#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("A_address0", 10, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("A_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("A_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("A_d0", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("A_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("addr_in_address0", 10, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("addr_in_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("addr_in_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("addr_out_address0", 10, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("addr_out_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("addr_out_q0", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("atanh_address0", 4, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("atanh_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("atanh_q0", 32, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("atanh_address1", 4, hls_out, 3, "ap_memory", "MemPortADDR2", 1),
	Port_Property("atanh_ce1", 1, hls_out, 3, "ap_memory", "MemPortCE2", 1),
	Port_Property("atanh_q1", 32, hls_in, 3, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("sinh_address0", 3, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("sinh_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("sinh_q0", 32, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("cosh_address0", 3, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("cosh_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("cosh_q0", 32, hls_in, 5, "ap_memory", "mem_dout", 1),
};
const char* HLS_Design_Meta::dut_name = "getTanh";
