#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("A_address0", 16, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("A_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("A_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("A_d0", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("A_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("A_address1", 16, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("A_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("A_q1", 32, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("u1_address0", 8, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("u1_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("u1_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("v1_address0", 8, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("v1_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("v1_q0", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("u2_address0", 8, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("u2_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("u2_q0", 32, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("v2_address0", 8, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("v2_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("v2_q0", 32, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("w_address0", 8, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("w_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("w_we0", 1, hls_out, 5, "ap_memory", "mem_we", 1),
	Port_Property("w_d0", 32, hls_out, 5, "ap_memory", "mem_din", 1),
	Port_Property("w_q0", 32, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("x_address0", 8, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("x_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("x_we0", 1, hls_out, 6, "ap_memory", "mem_we", 1),
	Port_Property("x_d0", 32, hls_out, 6, "ap_memory", "mem_din", 1),
	Port_Property("x_q0", 32, hls_in, 6, "ap_memory", "mem_dout", 1),
	Port_Property("y_address0", 8, hls_out, 7, "ap_memory", "mem_address", 1),
	Port_Property("y_ce0", 1, hls_out, 7, "ap_memory", "mem_ce", 1),
	Port_Property("y_q0", 32, hls_in, 7, "ap_memory", "mem_dout", 1),
	Port_Property("z_address0", 8, hls_out, 8, "ap_memory", "mem_address", 1),
	Port_Property("z_ce0", 1, hls_out, 8, "ap_memory", "mem_ce", 1),
	Port_Property("z_q0", 32, hls_in, 8, "ap_memory", "mem_dout", 1),
};
const char* HLS_Design_Meta::dut_name = "gemver";
