set SynModuleInfo {
  {SRCNAME substring_Pipeline_loop_0_VITIS_LOOP_31_1 MODELNAME substring_Pipeline_loop_0_VITIS_LOOP_31_1 RTLNAME substring_substring_Pipeline_loop_0_VITIS_LOOP_31_1
    SUBMODULES {
      {MODELNAME substring_flow_control_loop_pipe_sequential_init RTLNAME substring_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME substring_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME substring_Pipeline_loop_1_VITIS_LOOP_49_2 MODELNAME substring_Pipeline_loop_1_VITIS_LOOP_49_2 RTLNAME substring_substring_Pipeline_loop_1_VITIS_LOOP_49_2}
  {SRCNAME substring_Pipeline_loop_2_VITIS_LOOP_67_3 MODELNAME substring_Pipeline_loop_2_VITIS_LOOP_67_3 RTLNAME substring_substring_Pipeline_loop_2_VITIS_LOOP_67_3}
  {SRCNAME substring_Pipeline_loop_3_VITIS_LOOP_85_4 MODELNAME substring_Pipeline_loop_3_VITIS_LOOP_85_4 RTLNAME substring_substring_Pipeline_loop_3_VITIS_LOOP_85_4}
  {SRCNAME substring_Pipeline_loop_4_VITIS_LOOP_103_5 MODELNAME substring_Pipeline_loop_4_VITIS_LOOP_103_5 RTLNAME substring_substring_Pipeline_loop_4_VITIS_LOOP_103_5}
  {SRCNAME substring_Pipeline_loop_5_VITIS_LOOP_121_6 MODELNAME substring_Pipeline_loop_5_VITIS_LOOP_121_6 RTLNAME substring_substring_Pipeline_loop_5_VITIS_LOOP_121_6}
  {SRCNAME substring_Pipeline_loop_6_VITIS_LOOP_139_7 MODELNAME substring_Pipeline_loop_6_VITIS_LOOP_139_7 RTLNAME substring_substring_Pipeline_loop_6_VITIS_LOOP_139_7}
  {SRCNAME substring_Pipeline_loop_7_VITIS_LOOP_157_8 MODELNAME substring_Pipeline_loop_7_VITIS_LOOP_157_8 RTLNAME substring_substring_Pipeline_loop_7_VITIS_LOOP_157_8}
  {SRCNAME substring MODELNAME substring RTLNAME substring IS_TOP 1}
}
