#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("str_0_address0", 12, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("str_0_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("str_0_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("str_1_address0", 12, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("str_1_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("str_1_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("str_2_address0", 12, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("str_2_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("str_2_q0", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("str_3_address0", 12, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("str_3_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("str_3_q0", 32, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("str_4_address0", 12, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("str_4_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("str_4_q0", 32, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("str_5_address0", 12, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("str_5_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("str_5_q0", 32, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("str_6_address0", 12, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("str_6_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("str_6_q0", 32, hls_in, 6, "ap_memory", "mem_dout", 1),
	Port_Property("str_7_address0", 12, hls_out, 7, "ap_memory", "mem_address", 1),
	Port_Property("str_7_ce0", 1, hls_out, 7, "ap_memory", "mem_ce", 1),
	Port_Property("str_7_q0", 32, hls_in, 7, "ap_memory", "mem_dout", 1),
	Port_Property("ap_return", 32, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "substring";
