set SynModuleInfo {
  {SRCNAME _rand MODELNAME p_rand RTLNAME main_p_rand}
  {SRCNAME main_Pipeline_VITIS_LOOP_590_1 MODELNAME main_Pipeline_VITIS_LOOP_590_1 RTLNAME main_main_Pipeline_VITIS_LOOP_590_1
    SUBMODULES {
      {MODELNAME main_uitofp_32ns_32_7_no_dsp_1 RTLNAME main_uitofp_32ns_32_7_no_dsp_1 BINDTYPE op TYPE uitofp IMPL auto LATENCY 6 ALLOW_PRAGMA 1}
      {MODELNAME main_flow_control_loop_pipe_sequential_init RTLNAME main_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME main_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME main_Pipeline_VITIS_LOOP_610_2 MODELNAME main_Pipeline_VITIS_LOOP_610_2 RTLNAME main_main_Pipeline_VITIS_LOOP_610_2}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_40_1 MODELNAME matrixmult_Pipeline_VITIS_LOOP_40_1 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_40_1}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_48_2 MODELNAME matrixmult_Pipeline_VITIS_LOOP_48_2 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_48_2}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_56_3 MODELNAME matrixmult_Pipeline_VITIS_LOOP_56_3 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_56_3}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_64_4 MODELNAME matrixmult_Pipeline_VITIS_LOOP_64_4 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_64_4}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_72_5 MODELNAME matrixmult_Pipeline_VITIS_LOOP_72_5 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_72_5}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_80_6 MODELNAME matrixmult_Pipeline_VITIS_LOOP_80_6 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_80_6}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_88_7 MODELNAME matrixmult_Pipeline_VITIS_LOOP_88_7 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_88_7}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_96_8 MODELNAME matrixmult_Pipeline_VITIS_LOOP_96_8 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_96_8}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_108_9 MODELNAME matrixmult_Pipeline_VITIS_LOOP_108_9 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_108_9}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_116_10 MODELNAME matrixmult_Pipeline_VITIS_LOOP_116_10 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_116_10}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_124_11 MODELNAME matrixmult_Pipeline_VITIS_LOOP_124_11 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_124_11}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_132_12 MODELNAME matrixmult_Pipeline_VITIS_LOOP_132_12 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_132_12}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_140_13 MODELNAME matrixmult_Pipeline_VITIS_LOOP_140_13 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_140_13}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_148_14 MODELNAME matrixmult_Pipeline_VITIS_LOOP_148_14 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_148_14}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_156_15 MODELNAME matrixmult_Pipeline_VITIS_LOOP_156_15 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_156_15}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_164_16 MODELNAME matrixmult_Pipeline_VITIS_LOOP_164_16 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_164_16}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_176_17 MODELNAME matrixmult_Pipeline_VITIS_LOOP_176_17 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_176_17}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_184_18 MODELNAME matrixmult_Pipeline_VITIS_LOOP_184_18 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_184_18}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_192_19 MODELNAME matrixmult_Pipeline_VITIS_LOOP_192_19 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_192_19}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_200_20 MODELNAME matrixmult_Pipeline_VITIS_LOOP_200_20 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_200_20}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_208_21 MODELNAME matrixmult_Pipeline_VITIS_LOOP_208_21 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_208_21}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_216_22 MODELNAME matrixmult_Pipeline_VITIS_LOOP_216_22 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_216_22}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_224_23 MODELNAME matrixmult_Pipeline_VITIS_LOOP_224_23 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_224_23}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_232_24 MODELNAME matrixmult_Pipeline_VITIS_LOOP_232_24 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_232_24}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_244_25 MODELNAME matrixmult_Pipeline_VITIS_LOOP_244_25 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_244_25}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_252_26 MODELNAME matrixmult_Pipeline_VITIS_LOOP_252_26 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_252_26}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_260_27 MODELNAME matrixmult_Pipeline_VITIS_LOOP_260_27 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_260_27}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_268_28 MODELNAME matrixmult_Pipeline_VITIS_LOOP_268_28 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_268_28}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_276_29 MODELNAME matrixmult_Pipeline_VITIS_LOOP_276_29 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_276_29}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_284_30 MODELNAME matrixmult_Pipeline_VITIS_LOOP_284_30 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_284_30}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_292_31 MODELNAME matrixmult_Pipeline_VITIS_LOOP_292_31 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_292_31}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_300_32 MODELNAME matrixmult_Pipeline_VITIS_LOOP_300_32 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_300_32}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_312_33 MODELNAME matrixmult_Pipeline_VITIS_LOOP_312_33 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_312_33}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_320_34 MODELNAME matrixmult_Pipeline_VITIS_LOOP_320_34 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_320_34}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_328_35 MODELNAME matrixmult_Pipeline_VITIS_LOOP_328_35 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_328_35}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_336_36 MODELNAME matrixmult_Pipeline_VITIS_LOOP_336_36 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_336_36}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_344_37 MODELNAME matrixmult_Pipeline_VITIS_LOOP_344_37 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_344_37}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_352_38 MODELNAME matrixmult_Pipeline_VITIS_LOOP_352_38 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_352_38}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_360_39 MODELNAME matrixmult_Pipeline_VITIS_LOOP_360_39 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_360_39}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_368_40 MODELNAME matrixmult_Pipeline_VITIS_LOOP_368_40 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_368_40}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_380_41 MODELNAME matrixmult_Pipeline_VITIS_LOOP_380_41 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_380_41}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_388_42 MODELNAME matrixmult_Pipeline_VITIS_LOOP_388_42 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_388_42}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_396_43 MODELNAME matrixmult_Pipeline_VITIS_LOOP_396_43 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_396_43}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_404_44 MODELNAME matrixmult_Pipeline_VITIS_LOOP_404_44 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_404_44}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_412_45 MODELNAME matrixmult_Pipeline_VITIS_LOOP_412_45 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_412_45}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_420_46 MODELNAME matrixmult_Pipeline_VITIS_LOOP_420_46 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_420_46}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_428_47 MODELNAME matrixmult_Pipeline_VITIS_LOOP_428_47 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_428_47}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_436_48 MODELNAME matrixmult_Pipeline_VITIS_LOOP_436_48 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_436_48}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_448_49 MODELNAME matrixmult_Pipeline_VITIS_LOOP_448_49 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_448_49}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_456_50 MODELNAME matrixmult_Pipeline_VITIS_LOOP_456_50 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_456_50}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_464_51 MODELNAME matrixmult_Pipeline_VITIS_LOOP_464_51 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_464_51}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_472_52 MODELNAME matrixmult_Pipeline_VITIS_LOOP_472_52 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_472_52}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_480_53 MODELNAME matrixmult_Pipeline_VITIS_LOOP_480_53 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_480_53}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_488_54 MODELNAME matrixmult_Pipeline_VITIS_LOOP_488_54 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_488_54}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_496_55 MODELNAME matrixmult_Pipeline_VITIS_LOOP_496_55 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_496_55}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_504_56 MODELNAME matrixmult_Pipeline_VITIS_LOOP_504_56 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_504_56}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_516_57 MODELNAME matrixmult_Pipeline_VITIS_LOOP_516_57 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_516_57}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_524_58 MODELNAME matrixmult_Pipeline_VITIS_LOOP_524_58 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_524_58}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_532_59 MODELNAME matrixmult_Pipeline_VITIS_LOOP_532_59 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_532_59}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_540_60 MODELNAME matrixmult_Pipeline_VITIS_LOOP_540_60 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_540_60}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_548_61 MODELNAME matrixmult_Pipeline_VITIS_LOOP_548_61 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_548_61}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_556_62 MODELNAME matrixmult_Pipeline_VITIS_LOOP_556_62 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_556_62}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_564_63 MODELNAME matrixmult_Pipeline_VITIS_LOOP_564_63 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_564_63}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_572_64 MODELNAME matrixmult_Pipeline_VITIS_LOOP_572_64 RTLNAME main_matrixmult_Pipeline_VITIS_LOOP_572_64}
  {SRCNAME matrixmult MODELNAME matrixmult RTLNAME main_matrixmult
    SUBMODULES {
      {MODELNAME main_fmul_32ns_32ns_32_8_max_dsp_1 RTLNAME main_fmul_32ns_32ns_32_8_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME main_fcmp_32ns_32ns_1_4_no_dsp_1 RTLNAME main_fcmp_32ns_32ns_1_4_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME main_fadd_32ns_32ns_32_10_full_dsp_1 RTLNAME main_fadd_32ns_32ns_32_10_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 9 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME main MODELNAME main RTLNAME main IS_TOP 1
    SUBMODULES {
      {MODELNAME main_A_0_RAM_AUTO_1R1W RTLNAME main_A_0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME main_C_0_RAM_AUTO_0R0W RTLNAME main_C_0_RAM_AUTO_0R0W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
