set SynModuleInfo {
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_29_1 MODELNAME matrixmult_Pipeline_VITIS_LOOP_29_1 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_29_1
    SUBMODULES {
      {MODELNAME matrixmult_flow_control_loop_pipe_sequential_init RTLNAME matrixmult_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME matrixmult_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_37_2 MODELNAME matrixmult_Pipeline_VITIS_LOOP_37_2 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_37_2}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_45_3 MODELNAME matrixmult_Pipeline_VITIS_LOOP_45_3 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_45_3}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_53_4 MODELNAME matrixmult_Pipeline_VITIS_LOOP_53_4 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_53_4}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_61_5 MODELNAME matrixmult_Pipeline_VITIS_LOOP_61_5 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_61_5}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_69_6 MODELNAME matrixmult_Pipeline_VITIS_LOOP_69_6 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_69_6}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_77_7 MODELNAME matrixmult_Pipeline_VITIS_LOOP_77_7 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_77_7}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_85_8 MODELNAME matrixmult_Pipeline_VITIS_LOOP_85_8 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_85_8}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_97_9 MODELNAME matrixmult_Pipeline_VITIS_LOOP_97_9 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_97_9}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_105_10 MODELNAME matrixmult_Pipeline_VITIS_LOOP_105_10 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_105_10}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_113_11 MODELNAME matrixmult_Pipeline_VITIS_LOOP_113_11 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_113_11}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_121_12 MODELNAME matrixmult_Pipeline_VITIS_LOOP_121_12 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_121_12}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_129_13 MODELNAME matrixmult_Pipeline_VITIS_LOOP_129_13 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_129_13}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_137_14 MODELNAME matrixmult_Pipeline_VITIS_LOOP_137_14 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_137_14}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_145_15 MODELNAME matrixmult_Pipeline_VITIS_LOOP_145_15 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_145_15}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_153_16 MODELNAME matrixmult_Pipeline_VITIS_LOOP_153_16 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_153_16}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_165_17 MODELNAME matrixmult_Pipeline_VITIS_LOOP_165_17 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_165_17}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_173_18 MODELNAME matrixmult_Pipeline_VITIS_LOOP_173_18 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_173_18}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_181_19 MODELNAME matrixmult_Pipeline_VITIS_LOOP_181_19 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_181_19}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_189_20 MODELNAME matrixmult_Pipeline_VITIS_LOOP_189_20 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_189_20}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_197_21 MODELNAME matrixmult_Pipeline_VITIS_LOOP_197_21 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_197_21}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_205_22 MODELNAME matrixmult_Pipeline_VITIS_LOOP_205_22 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_205_22}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_213_23 MODELNAME matrixmult_Pipeline_VITIS_LOOP_213_23 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_213_23}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_221_24 MODELNAME matrixmult_Pipeline_VITIS_LOOP_221_24 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_221_24}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_233_25 MODELNAME matrixmult_Pipeline_VITIS_LOOP_233_25 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_233_25}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_241_26 MODELNAME matrixmult_Pipeline_VITIS_LOOP_241_26 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_241_26}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_249_27 MODELNAME matrixmult_Pipeline_VITIS_LOOP_249_27 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_249_27}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_257_28 MODELNAME matrixmult_Pipeline_VITIS_LOOP_257_28 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_257_28}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_265_29 MODELNAME matrixmult_Pipeline_VITIS_LOOP_265_29 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_265_29}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_273_30 MODELNAME matrixmult_Pipeline_VITIS_LOOP_273_30 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_273_30}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_281_31 MODELNAME matrixmult_Pipeline_VITIS_LOOP_281_31 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_281_31}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_289_32 MODELNAME matrixmult_Pipeline_VITIS_LOOP_289_32 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_289_32}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_301_33 MODELNAME matrixmult_Pipeline_VITIS_LOOP_301_33 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_301_33}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_309_34 MODELNAME matrixmult_Pipeline_VITIS_LOOP_309_34 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_309_34}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_317_35 MODELNAME matrixmult_Pipeline_VITIS_LOOP_317_35 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_317_35}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_325_36 MODELNAME matrixmult_Pipeline_VITIS_LOOP_325_36 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_325_36}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_333_37 MODELNAME matrixmult_Pipeline_VITIS_LOOP_333_37 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_333_37}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_341_38 MODELNAME matrixmult_Pipeline_VITIS_LOOP_341_38 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_341_38}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_349_39 MODELNAME matrixmult_Pipeline_VITIS_LOOP_349_39 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_349_39}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_357_40 MODELNAME matrixmult_Pipeline_VITIS_LOOP_357_40 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_357_40}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_369_41 MODELNAME matrixmult_Pipeline_VITIS_LOOP_369_41 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_369_41}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_377_42 MODELNAME matrixmult_Pipeline_VITIS_LOOP_377_42 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_377_42}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_385_43 MODELNAME matrixmult_Pipeline_VITIS_LOOP_385_43 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_385_43}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_393_44 MODELNAME matrixmult_Pipeline_VITIS_LOOP_393_44 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_393_44}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_401_45 MODELNAME matrixmult_Pipeline_VITIS_LOOP_401_45 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_401_45}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_409_46 MODELNAME matrixmult_Pipeline_VITIS_LOOP_409_46 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_409_46}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_417_47 MODELNAME matrixmult_Pipeline_VITIS_LOOP_417_47 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_417_47}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_425_48 MODELNAME matrixmult_Pipeline_VITIS_LOOP_425_48 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_425_48}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_437_49 MODELNAME matrixmult_Pipeline_VITIS_LOOP_437_49 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_437_49}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_445_50 MODELNAME matrixmult_Pipeline_VITIS_LOOP_445_50 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_445_50}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_453_51 MODELNAME matrixmult_Pipeline_VITIS_LOOP_453_51 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_453_51}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_461_52 MODELNAME matrixmult_Pipeline_VITIS_LOOP_461_52 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_461_52}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_469_53 MODELNAME matrixmult_Pipeline_VITIS_LOOP_469_53 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_469_53}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_477_54 MODELNAME matrixmult_Pipeline_VITIS_LOOP_477_54 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_477_54}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_485_55 MODELNAME matrixmult_Pipeline_VITIS_LOOP_485_55 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_485_55}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_493_56 MODELNAME matrixmult_Pipeline_VITIS_LOOP_493_56 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_493_56}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_505_57 MODELNAME matrixmult_Pipeline_VITIS_LOOP_505_57 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_505_57}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_513_58 MODELNAME matrixmult_Pipeline_VITIS_LOOP_513_58 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_513_58}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_521_59 MODELNAME matrixmult_Pipeline_VITIS_LOOP_521_59 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_521_59}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_529_60 MODELNAME matrixmult_Pipeline_VITIS_LOOP_529_60 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_529_60}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_537_61 MODELNAME matrixmult_Pipeline_VITIS_LOOP_537_61 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_537_61}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_545_62 MODELNAME matrixmult_Pipeline_VITIS_LOOP_545_62 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_545_62}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_553_63 MODELNAME matrixmult_Pipeline_VITIS_LOOP_553_63 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_553_63}
  {SRCNAME matrixmult_Pipeline_VITIS_LOOP_561_64 MODELNAME matrixmult_Pipeline_VITIS_LOOP_561_64 RTLNAME matrixmult_matrixmult_Pipeline_VITIS_LOOP_561_64}
  {SRCNAME matrixmult MODELNAME matrixmult RTLNAME matrixmult IS_TOP 1
    SUBMODULES {
      {MODELNAME matrixmult_fadd_32ns_32ns_32_5_full_dsp_1 RTLNAME matrixmult_fadd_32ns_32ns_32_5_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME matrixmult_fmul_32ns_32ns_32_4_max_dsp_1 RTLNAME matrixmult_fmul_32ns_32ns_32_4_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME matrixmult_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME matrixmult_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
    }
  }
}
