set_property SRC_FILE_INFO {cfile:/home/gabriel/Documents/UFRGS/RAISE/AHLS/AHLS/hls/vitis_projects/chstone/adpcm/solution1/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/adpcm_main_ooc.xdc rfile:../../../../../project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/adpcm_main_ooc.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gabriel/Documents/UFRGS/RAISE/AHLS/AHLS/hls/vitis_projects/chstone/adpcm/solution1/impl/verilog/project.runs/bd_0_hls_inst_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 5.000 -name ap_clk [get_ports ap_clk]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst]
