// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="gemver_gemver,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu35p-fsvh2104-1-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.579000,HLS_SYN_LAT=852019,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2385,HLS_SYN_LUT=2121,HLS_VERSION=2023_2}" *)

module gemver (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_we0,
        A_d0,
        A_q0,
        A_address1,
        A_ce1,
        A_q1,
        u1_address0,
        u1_ce0,
        u1_q0,
        v1_address0,
        v1_ce0,
        v1_q0,
        u2_address0,
        u2_ce0,
        u2_q0,
        v2_address0,
        v2_ce0,
        v2_q0,
        w_address0,
        w_ce0,
        w_we0,
        w_d0,
        w_q0,
        x_address0,
        x_ce0,
        x_we0,
        x_d0,
        x_q0,
        y_address0,
        y_ce0,
        y_q0,
        z_address0,
        z_ce0,
        z_q0
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] A_address0;
output   A_ce0;
output   A_we0;
output  [31:0] A_d0;
input  [31:0] A_q0;
output  [15:0] A_address1;
output   A_ce1;
input  [31:0] A_q1;
output  [7:0] u1_address0;
output   u1_ce0;
input  [31:0] u1_q0;
output  [7:0] v1_address0;
output   v1_ce0;
input  [31:0] v1_q0;
output  [7:0] u2_address0;
output   u2_ce0;
input  [31:0] u2_q0;
output  [7:0] v2_address0;
output   v2_ce0;
input  [31:0] v2_q0;
output  [7:0] w_address0;
output   w_ce0;
output   w_we0;
output  [31:0] w_d0;
input  [31:0] w_q0;
output  [7:0] x_address0;
output   x_ce0;
output   x_we0;
output  [31:0] x_d0;
input  [31:0] x_q0;
output  [7:0] y_address0;
output   y_ce0;
input  [31:0] y_q0;
output  [7:0] z_address0;
output   z_ce0;
input  [31:0] z_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] A_address0;
reg A_ce0;
reg A_we0;
reg A_ce1;
reg[7:0] x_address0;
reg x_ce0;
reg x_we0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_start;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_done;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_idle;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_ready;
wire   [7:0] grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_u1_address0;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_u1_ce0;
wire   [7:0] grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_u2_address0;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_u2_ce0;
wire   [7:0] grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_v1_address0;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_v1_ce0;
wire   [7:0] grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_v2_address0;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_v2_ce0;
wire   [15:0] grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_address0;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_ce0;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_we0;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_d0;
wire   [15:0] grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_address1;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_ce1;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_76_p_din0;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_76_p_din1;
wire   [1:0] grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_76_p_opcode;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_76_p_ce;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_80_p_din0;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_80_p_din1;
wire    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_80_p_ce;
wire    grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_start;
wire    grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_done;
wire    grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_idle;
wire    grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_ready;
wire   [15:0] grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_A_address0;
wire    grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_A_ce0;
wire   [7:0] grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_y_address0;
wire    grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_y_ce0;
wire   [7:0] grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_z_address0;
wire    grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_z_ce0;
wire   [7:0] grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_x_address0;
wire    grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_x_ce0;
wire    grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_x_we0;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_x_d0;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_76_p_din0;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_76_p_din1;
wire   [1:0] grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_76_p_opcode;
wire    grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_76_p_ce;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_80_p_din0;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_80_p_din1;
wire    grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_80_p_ce;
wire    grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_start;
wire    grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_done;
wire    grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_idle;
wire    grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_ready;
wire   [15:0] grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_A_address0;
wire    grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_A_ce0;
wire   [7:0] grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_x_address0;
wire    grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_x_ce0;
wire   [7:0] grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_w_address0;
wire    grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_w_ce0;
wire    grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_w_we0;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_w_d0;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_76_p_din0;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_76_p_din1;
wire   [1:0] grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_76_p_opcode;
wire    grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_76_p_ce;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_80_p_din0;
wire   [31:0] grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_80_p_din1;
wire    grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_80_p_ce;
reg    grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_start_reg;
reg   [5:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [31:0] grp_fu_76_p2;
reg   [31:0] grp_fu_76_p0;
reg   [31:0] grp_fu_76_p1;
reg    grp_fu_76_ce;
wire   [31:0] grp_fu_80_p2;
reg   [31:0] grp_fu_80_p0;
reg   [31:0] grp_fu_80_p1;
reg    grp_fu_80_ce;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_start_reg = 1'b0;
#0 grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_start_reg = 1'b0;
#0 grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_start_reg = 1'b0;
end

gemver_gemver_Pipeline_VITIS_LOOP_14_1_loop_2 grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_start),
    .ap_done(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_done),
    .ap_idle(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_idle),
    .ap_ready(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_ready),
    .u1_address0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_u1_address0),
    .u1_ce0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_u1_ce0),
    .u1_q0(u1_q0),
    .u2_address0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_u2_address0),
    .u2_ce0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_u2_ce0),
    .u2_q0(u2_q0),
    .v1_address0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_v1_address0),
    .v1_ce0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_v1_ce0),
    .v1_q0(v1_q0),
    .v2_address0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_v2_address0),
    .v2_ce0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_v2_ce0),
    .v2_q0(v2_q0),
    .A_address0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_address0),
    .A_ce0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_ce0),
    .A_we0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_we0),
    .A_d0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_d0),
    .A_address1(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_address1),
    .A_ce1(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_ce1),
    .A_q1(A_q1),
    .grp_fu_76_p_din0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_76_p_din0),
    .grp_fu_76_p_din1(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_76_p_din1),
    .grp_fu_76_p_opcode(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_76_p_opcode),
    .grp_fu_76_p_dout0(grp_fu_76_p2),
    .grp_fu_76_p_ce(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_76_p_ce),
    .grp_fu_80_p_din0(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_80_p_din0),
    .grp_fu_80_p_din1(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_80_p_din1),
    .grp_fu_80_p_dout0(grp_fu_80_p2),
    .grp_fu_80_p_ce(grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_80_p_ce)
);

gemver_gemver_Pipeline_VITIS_LOOP_23_2_loop_3 grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_start),
    .ap_done(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_done),
    .ap_idle(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_idle),
    .ap_ready(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_ready),
    .A_address0(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_A_address0),
    .A_ce0(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_A_ce0),
    .A_q0(A_q0),
    .y_address0(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_y_address0),
    .y_ce0(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_y_ce0),
    .y_q0(y_q0),
    .z_address0(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_z_address0),
    .z_ce0(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_z_ce0),
    .z_q0(z_q0),
    .x_address0(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_x_address0),
    .x_ce0(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_x_ce0),
    .x_we0(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_x_we0),
    .x_d0(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_x_d0),
    .x_q0(x_q0),
    .grp_fu_76_p_din0(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_76_p_din0),
    .grp_fu_76_p_din1(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_76_p_din1),
    .grp_fu_76_p_opcode(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_76_p_opcode),
    .grp_fu_76_p_dout0(grp_fu_76_p2),
    .grp_fu_76_p_ce(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_76_p_ce),
    .grp_fu_80_p_din0(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_80_p_din0),
    .grp_fu_80_p_din1(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_80_p_din1),
    .grp_fu_80_p_dout0(grp_fu_80_p2),
    .grp_fu_80_p_ce(grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_80_p_ce)
);

gemver_gemver_Pipeline_VITIS_LOOP_35_3_loop_4 grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_start),
    .ap_done(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_done),
    .ap_idle(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_idle),
    .ap_ready(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_ready),
    .A_address0(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_A_address0),
    .A_ce0(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_A_ce0),
    .A_q0(A_q0),
    .x_address0(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_x_address0),
    .x_ce0(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_x_ce0),
    .x_q0(x_q0),
    .w_address0(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_w_address0),
    .w_ce0(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_w_ce0),
    .w_we0(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_w_we0),
    .w_d0(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_w_d0),
    .w_q0(w_q0),
    .grp_fu_76_p_din0(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_76_p_din0),
    .grp_fu_76_p_din1(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_76_p_din1),
    .grp_fu_76_p_opcode(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_76_p_opcode),
    .grp_fu_76_p_dout0(grp_fu_76_p2),
    .grp_fu_76_p_ce(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_76_p_ce),
    .grp_fu_80_p_din0(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_80_p_din0),
    .grp_fu_80_p_din1(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_80_p_din1),
    .grp_fu_80_p_dout0(grp_fu_80_p2),
    .grp_fu_80_p_ce(grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_80_p_ce)
);

gemver_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_76_p0),
    .din1(grp_fu_76_p1),
    .ce(grp_fu_76_ce),
    .dout(grp_fu_76_p2)
);

gemver_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_80_p0),
    .din1(grp_fu_80_p1),
    .ce(grp_fu_80_ce),
    .dout(grp_fu_80_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_start_reg <= 1'b1;
        end else if ((grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_ready == 1'b1)) begin
            grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_start_reg <= 1'b1;
        end else if ((grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_ready == 1'b1)) begin
            grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_start_reg <= 1'b1;
        end else if ((grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_ready == 1'b1)) begin
            grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_address0 = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_address0 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_address0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_address0;
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_ce0 = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_ce0 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_ce0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_ce0;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_ce1 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_ce1;
    end else begin
        A_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_we0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_we0;
    end else begin
        A_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_76_ce = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_76_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_76_ce = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_76_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_76_ce = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_76_p_ce;
    end else begin
        grp_fu_76_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_76_p0 = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_76_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_76_p0 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_76_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_76_p0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_76_p_din0;
    end else begin
        grp_fu_76_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_76_p1 = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_76_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_76_p1 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_76_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_76_p1 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_76_p_din1;
    end else begin
        grp_fu_76_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_80_ce = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_80_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_80_ce = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_80_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_80_ce = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_80_p_ce;
    end else begin
        grp_fu_80_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_80_p0 = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_80_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_80_p0 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_80_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_80_p0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_80_p_din0;
    end else begin
        grp_fu_80_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_80_p1 = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_grp_fu_80_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_80_p1 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_grp_fu_80_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_80_p1 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_grp_fu_80_p_din1;
    end else begin
        grp_fu_80_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_address0 = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        x_address0 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_x_address0;
    end else begin
        x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_ce0 = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        x_ce0 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_x_ce0;
    end else begin
        x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        x_we0 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_x_we0;
    end else begin
        x_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address1 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_address1;

assign A_d0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_A_d0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

assign grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_start = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_ap_start_reg;

assign grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_start = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_ap_start_reg;

assign grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_start = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_ap_start_reg;

assign u1_address0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_u1_address0;

assign u1_ce0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_u1_ce0;

assign u2_address0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_u2_address0;

assign u2_ce0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_u2_ce0;

assign v1_address0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_v1_address0;

assign v1_ce0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_v1_ce0;

assign v2_address0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_v2_address0;

assign v2_ce0 = grp_gemver_Pipeline_VITIS_LOOP_14_1_loop_2_fu_40_v2_ce0;

assign w_address0 = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_w_address0;

assign w_ce0 = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_w_ce0;

assign w_d0 = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_w_d0;

assign w_we0 = grp_gemver_Pipeline_VITIS_LOOP_35_3_loop_4_fu_66_w_we0;

assign x_d0 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_x_d0;

assign y_address0 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_y_address0;

assign y_ce0 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_y_ce0;

assign z_address0 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_z_address0;

assign z_ce0 = grp_gemver_Pipeline_VITIS_LOOP_23_2_loop_3_fu_54_z_ce0;

endmodule //gemver
